import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Wallet } from "../components/Wallet";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const cabinet_grotesk = localFont({
  src: [
    {
      path: "../public/assets/fonts/cabinet-grotesk/CabinetGrotesk-Extrabold.otf",
      weight: "800",
    },
    {
      path: "../public/assets/fonts/cabinet-grotesk/CabinetGrotesk-Bold.otf",
      weight: "700",
    },
  ],
  variable: "--font-cabinet_grotesk",
});

const sn_pro = localFont({
  src: [
    {
      path: "../public/assets/fonts/sn-pro_5.0.1/ttf/sn-pro-latin-600-normal.ttf",
      weight: "600",
    },
    {
      path: "../public/assets/fonts/sn-pro_5.0.1/ttf/sn-pro-latin-500-normal.ttf",
      weight: "500",
    },
  ],
  variable: "--font-sn_pro",
});

export const metadata: Metadata = {
  title: "Solgacy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cabinet_grotesk} ${sn_pro}`}>
        <div>
          <Wallet>
            <div>
              {children}
              <ToastContainer />
            </div>
          </Wallet>
        </div>
      </body>
    </html>
  );
}
